# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Lenovo\Desktop\Projeler\Lolmatic\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(325, 81)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.nick = QtWidgets.QLineEdit(self.centralwidget)
        self.nick.setGeometry(QtCore.QRect(10, 30, 113, 20))
        self.nick.setObjectName("nick")
        self.region = QtWidgets.QComboBox(self.centralwidget)
        self.region.setGeometry(QtCore.QRect(140, 30, 69, 22))
        self.region.setObjectName("region")
        self.region.addItem("")
        self.region.addItem("")
        self.region.addItem("")
        self.region.addItem("")
        self.region.addItem("")
        self.region.addItem("")
        self.region.addItem("")
        self.region.addItem("")
        self.region.addItem("")
        self.region.addItem("")
        self.region.addItem("")
        self.ara = QtWidgets.QPushButton(self.centralwidget)
        self.ara.setGeometry(QtCore.QRect(230, 30, 75, 23))
        self.ara.setAutoDefault(True)
        self.ara.setDefault(True)
        self.ara.setObjectName("ara")
        self.l_sihirdar_adi = QtWidgets.QLabel(self.centralwidget)
        self.l_sihirdar_adi.setGeometry(QtCore.QRect(30, 10, 61, 16))
        self.l_sihirdar_adi.setObjectName("l_sihirdar_adi")
        self.l_bolge = QtWidgets.QLabel(self.centralwidget)
        self.l_bolge.setGeometry(QtCore.QRect(160, 10, 31, 16))
        self.l_bolge.setObjectName("l_bolge")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nick.setText(_translate("MainWindow", "CyberTR10"))
        self.region.setItemText(0, _translate("MainWindow", "TR1"))
        self.region.setItemText(1, _translate("MainWindow", "BR1"))
        self.region.setItemText(2, _translate("MainWindow", "EUN1"))
        self.region.setItemText(3, _translate("MainWindow", "EUW1"))
        self.region.setItemText(4, _translate("MainWindow", "JP1"))
        self.region.setItemText(5, _translate("MainWindow", "KR"))
        self.region.setItemText(6, _translate("MainWindow", "LA1"))
        self.region.setItemText(7, _translate("MainWindow", "LA2"))
        self.region.setItemText(8, _translate("MainWindow", "NA1"))
        self.region.setItemText(9, _translate("MainWindow", "OC1"))
        self.region.setItemText(10, _translate("MainWindow", "RU"))
        self.ara.setText(_translate("MainWindow", "ARA"))
        self.l_sihirdar_adi.setText(_translate("MainWindow", "Sihirdar Adı"))
        self.l_bolge.setText(_translate("MainWindow", "Bölge"))
